version: "3"
services:
  hfss-twilio:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hfss-twilio
    container_name: hfss-twilio
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
